# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2023 Microchip Technology Inc. and its subsidiaries
#
# Author: Manikandan Muralidharan <manikandan.m@microchip.com>

obj-y += sam9x75_curiosity.o
