# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2026 Microchip Technology Inc. and its subsidiaries
#
# Author: Varshini Rajendran <varshini.rajendran@microchip.com>

obj-y += sam9x60_curiosity_pro.o
